### ISSUE TITLE
Wheels not showing up in Rviz

### ISSUE THREAD

**Issue by marco-monforte** [pvandervelde/zinger_ignition#2]
Hi Petrik,

First of all, thanks for making this very cool project open-source!

I'm trying to run everything (ignition, controller, localization, and navigation) but, when launching the robot, I can't see the wheels and get this error message in the RobotModel display. Would you happen to know how to fix it?

![image](https://github.com/pvandervelde/zinger_ignition/assets/32684998/604cbcfc-8d58-4739-be1e-f70496a9fa02)

![image](https://github.com/pvandervelde/zinger_ignition/assets/32684998/0ae02f7f-5ab4-4f13-8f9c-d216180e0dbb)

I've also tried launching the zinger_swerve_controller.

**Comment by marco-monforte** [comment]
PS: there's a typo in this repo's README.md and the zinger_nav. The launch command should be ``ros2 launch zinger_ignition ignition.launch.py rviz:=true world:=empty_world`` instead of ``ignition_launch``

**Comment by pvandervelde** [comment]
Did you set the fixed frame in Rviz to `map`? If you don't I think you get the result you found. I updated the readme for the nav package recently to indicate that you need to do that in pvandervelde/zinger_nav#2. You can find that comment here: https://github.com/pvandervelde/zinger_nav/blob/2895c841b3ffb2f669c4adfa75e789a152eea94a/README.md?plain=1#L95.

And thanks for pointing out the typo's. I've pushed some fixes

**Comment by marco-monforte** [comment]
I did, but apparently, the map is not being published. I get this error on the nav2.launch.py terminal:
```
[planner_server-3] [INFO] [1718270490.782627877] [global_costmap.global_costmap]: Timed out waiting for transform from base_footprint to map to become available, tf error: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
```

But also doing ```ros2 topic echo map``` shows the topic to exist but nothing getting through

I see the localization.launch.yaml in the nav2 package is not used anymore, but then I don't know where the map should come from

**Comment by pvandervelde** [comment]
Ooh are you running the zinger_swerve_controller? That publishes a transform from `base_footprint` to `odom` and then nav creates the transform from `odom` to `map` I think.

**Comment by alperen-keser** [comment]
First of all, thanks for all the hard work. 
I have the same problem with @marco-monforte, when launching the robot, I also can't see the wheels and get the same error messages.

I followed your updated README.md in zinger_nav and followed all the instructions (running 4 different .launch files) but the errors are still there? Could you help me out?

**Comment by pvandervelde** [comment]
I'll try to help. First can you tell me what you are running (i.e. which ROS nodes, and which Gazebo world etc.)? And can you share any logs you have? Are there any errors?

**Comment by chifongip** [comment]
You should start the simulation by pressing the play button at the bottom left corner of Ignition, or by adding the ```-r``` flag in ignition.launch.py.  

```
    ignition_gazebo = IncludeLaunchDescription(
        PythonLaunchDescriptionSource([ign_gazebo_launch]),
        launch_arguments=[
            ('ign_args', [LaunchConfiguration('world'),
                          '.sdf',
                          ' -r',
                          ' -v 4',
                          ' --gui-config ',
                          PathJoinSubstitution(
                            [pkg_ignition_bringup,
                             'gui',
                             'gui.config'])])
        ]
    )
```  

Wait a few seconds and Rviz will work properly.
